- hosts: all 
  become: true
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Send message to Discord if a reboot is needed
      uri:
        url: "{{ lookup('env', 'DISCORD_WEBHOOK') }}"
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
        body:
          content: "A reboot is required on {{ inventory_hostname }}"
      when: reboot_required_file.stat.exists